# Generated by Django 3.2.8 on 2022-01-11 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('vender', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('followees', models.ManyToManyField(related_name='_profiles_profile_followees_+', through='profiles.FriendShip', to='profiles.Profile', verbose_name='フォロー中')),
                ('followers', models.ManyToManyField(related_name='_profiles_profile_followers_+', through='profiles.FriendShip', to='profiles.Profile', verbose_name='フォロワー')),
            ],
        ),
    ]
