# Generated by Django 3.2.8 on 2022-01-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favostock',
            name='user',
        ),
    ]
