# Generated by Django 3.2.8 on 2022-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_favostock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favostock',
            name='description',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favostock',
            name='is_eod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favostock',
            name='is_fh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favostock',
            name='is_fmp',
            field=models.BooleanField(default=False),
        ),
    ]
