# Generated by Django 3.2.8 on 2022-01-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220109_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='favostock',
            name='isin',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
