# Generated by Django 3.2.8 on 2022-01-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_favostock_isin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favostock',
            old_name='ticker',
            new_name='symbol',
        ),
    ]
