# Generated by Django 3.2.8 on 2022-01-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('symbol_type', models.CharField(blank=True, max_length=50)),
                ('exchange', models.CharField(blank=True, max_length=100)),
                ('vender', models.CharField(max_length=3)),
                ('voters', models.ManyToManyField(related_name='like', to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
