# Generated by Django 3.2.8 on 2022-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_like', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='symbol',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='stocks.Symbol'),
        ),
    ]
