# Generated by Django 3.2.8 on 2022-02-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20220204_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='symbol',
            new_name='symbols',
        ),
    ]
