# Generated by Django 3.2.8 on 2022-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20220212_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymetric',
            name='ajustment',
        ),
        migrations.AddField(
            model_name='keymetric',
            name='changes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='symbol',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='keymetric',
            name='cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keymetric',
            name='deRation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keymetric',
            name='opGrowth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keymetric',
            name='peRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keymetric',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keymetric',
            name='roe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
