# Generated by Django 3.2.8 on 2022-01-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20220129_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesymbol',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stocks.symbol'),
        ),
    ]
