# Generated by Django 3.2.8 on 2022-01-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_favoritesymbol_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stocks.symbol'),
        ),
        migrations.AlterField(
            model_name='favoritesymbol',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.symbol'),
        ),
    ]
