# Generated by Django 3.2.8 on 2022-01-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20220129_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='symbol',
            name='tags',
            field=models.ManyToManyField(blank=True, to='stocks.Tag'),
        ),
    ]
